void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int mend(int num, int num1);
int sqroot(int num, int num1);
int is_prime_number(int n);
int ease(int num, int num1);
int palind(char *c, int num);
int is_palindrome(char *s);
int getLen(char *c);
int srch(char *x, char z, int num, int num1);
int wildcmp(char *s1, char *s2);
